local test_helper = require("spec.test_helper")
test_helper.setup_lua_path()

describe("CEL Basic Functionality", function()
  local cel

  before_each(function()
    cel = require("cel")
  end)

  describe("Module Loading", function()
    it("should load the CEL module successfully", function()
      assert.is_not_nil(cel)
      assert.is_not_nil(cel.context)
      assert.is_not_nil(cel.program)
    end)

    it("should create context instances", function()
      local ctx = cel.context.new()
      assert.is_not_nil(ctx)
    end)

    it("should create program instances", function()
      local prog = cel.program.new()
      assert.is_not_nil(prog)
    end)
  end)

  describe("Basic Arithmetic", function()
    it("should evaluate simple addition", function()
      local result, err = test_helper.eval_expression(cel, "1 + 2")
      assert.is_nil(err)
      assert.equals(3, result)
    end)

    it("should evaluate multiplication and addition", function()
      local result, err = test_helper.eval_expression(cel, "1 + 2 * 3")
      assert.is_nil(err)
      assert.equals(7, result)
    end)

    it("should evaluate parentheses", function()
      local result, err = test_helper.eval_expression(cel, "(1 + 2) * 3")
      assert.is_nil(err)
      assert.equals(9, result)
    end)

    it("should handle floating point arithmetic", function()
      local result, err = test_helper.eval_expression(cel, "1.5 + 2.5")
      assert.is_nil(err)
      assert.equals(4.0, result)
    end)

    it("should handle division", function()
      local result, err = test_helper.eval_expression(cel, "10 / 2")
      assert.is_nil(err)
      assert.equals(5, result)
    end)
  end)

  describe("Boolean Operations", function()
    it("should evaluate boolean literals", function()
      local result, err = test_helper.eval_expression(cel, "true")
      assert.is_nil(err)
      assert.is_true(result)

      result, err = test_helper.eval_expression(cel, "false")
      assert.is_nil(err)
      assert.is_false(result)
    end)

    it("should evaluate logical AND", function()
      local result, err = test_helper.eval_expression(cel, "true && false")
      assert.is_nil(err)
      assert.is_false(result)

      result, err = test_helper.eval_expression(cel, "true && true")
      assert.is_nil(err)
      assert.is_true(result)
    end)

    it("should evaluate logical OR", function()
      local result, err = test_helper.eval_expression(cel, "true || false")
      assert.is_nil(err)
      assert.is_true(result)

      result, err = test_helper.eval_expression(cel, "false || false")
      assert.is_nil(err)
      assert.is_false(result)
    end)

    it("should evaluate logical NOT", function()
      local result, err = test_helper.eval_expression(cel, "!true")
      assert.is_nil(err)
      assert.is_false(result)

      result, err = test_helper.eval_expression(cel, "!false")
      assert.is_nil(err)
      assert.is_true(result)
    end)
  end)

  describe("Comparison Operations", function()
    it("should evaluate equality", function()
      local result, err = test_helper.eval_expression(cel, "5 == 5")
      assert.is_nil(err)
      assert.is_true(result)

      result, err = test_helper.eval_expression(cel, "5 == 4")
      assert.is_nil(err)
      assert.is_false(result)
    end)

    it("should evaluate inequality", function()
      local result, err = test_helper.eval_expression(cel, "5 != 4")
      assert.is_nil(err)
      assert.is_true(result)

      result, err = test_helper.eval_expression(cel, "5 != 5")
      assert.is_nil(err)
      assert.is_false(result)
    end)

    it("should evaluate less than", function()
      local result, err = test_helper.eval_expression(cel, "3 < 5")
      assert.is_nil(err)
      assert.is_true(result)

      result, err = test_helper.eval_expression(cel, "5 < 3")
      assert.is_nil(err)
      assert.is_false(result)
    end)

    it("should evaluate greater than", function()
      local result, err = test_helper.eval_expression(cel, "5 > 3")
      assert.is_nil(err)
      assert.is_true(result)

      result, err = test_helper.eval_expression(cel, "3 > 5")
      assert.is_nil(err)
      assert.is_false(result)
    end)

    it("should evaluate less than or equal", function()
      local result, err = test_helper.eval_expression(cel, "3 <= 5")
      assert.is_nil(err)
      assert.is_true(result)

      result, err = test_helper.eval_expression(cel, "5 <= 5")
      assert.is_nil(err)
      assert.is_true(result)
    end)

    it("should evaluate greater than or equal", function()
      local result, err = test_helper.eval_expression(cel, "5 >= 3")
      assert.is_nil(err)
      assert.is_true(result)

      result, err = test_helper.eval_expression(cel, "5 >= 5")
      assert.is_nil(err)
      assert.is_true(result)
    end)
  end)
end)
