# Ignore all and define exceptions below
# This file is used to specify files and directories that should be ignored by Docker when building images
*

!hack/tooling/test-dependencies-0.1.0-0.rockspec
!hack/tooling/busted
